// Emits notes-editor/notes_editor.qrc from the built dist/.
//
// Why a generated qrc rather than a checked-in one: Vite emits content-hashed
// filenames (assets/index-B4mzf3TH.js), so every rebuild renames the files. A
// hand-maintained qrc would name files that no longer exist, and the failure
// mode is bad - `rcc` fails at build time on a *stale* qrc, which reads like a
// broken checkout rather than "you forgot to regenerate".
//
// rcc errors loudly on a missing file, so a qrc that disagrees with dist/ can
// never be linked into a binary. That is the property worth having: the failure
// lands at build time, not as a blank editor in a shipped release.
//
// Regenerated by `npm run build` (see the build:qrc step), so the normal
// workflow is just `npm run build`.

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const distDir = join(here, "..", "dist");
const qrcPath = join(here, "..", "notes_editor.qrc");

// rcc resolves <file> paths relative to the .qrc's own location, not to this
// script. Getting this wrong yields "../dist/..." which rcc accepts at
// generation time and then fails to find at link time with a bare
// "No rule to make target 'dist/index.html'".
const qrcDir = dirname(qrcPath);

/** Prefix the files land under inside the binary. Must match editorUrl in QML. */
const PREFIX = "/notes-editor";

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

let files;
try {
  files = walk(distDir);
} catch {
  console.error(
    `[qrc] ${distDir} does not exist. Run \`npm run build\` (or \`npm run dev\` for a dev build) first.`,
  );
  process.exit(1);
}

if (files.length === 0) {
  console.error(`[qrc] ${distDir} is empty - the Vite build produced nothing.`);
  process.exit(1);
}

if (!files.some((f) => f.endsWith(`${sep}index.html`))) {
  console.error(`[qrc] ${distDir} has no index.html; refusing to emit a qrc.`);
  process.exit(1);
}

// Sorted so the generated file is stable across runs on the same dist, which
// keeps it out of spurious diffs.
files.sort();

const body = files
  .map((f) => {
    // Alias keeps the in-binary path identical to the on-disk relative path,
    // which is what `base: "./"` in vite.config.ts makes the bundle expect.
    const alias = relative(distDir, f).split(sep).join("/");
    const src = relative(qrcDir, f).split(sep).join("/");
    return `        <file alias="${alias}">${src}</file>`;
  })
  .join("\n");

const xml = `<RCC>
    <!--
        GENERATED by scripts/emit-qrc.mjs - do not edit by hand.

        Sources notes-editor/dist/ into :/notes-editor/. Regenerate with
        \`npm run build\` in notes-editor/.

        Regenerated rather than committed by hand because Vite's content-hashed
        filenames change on every build. rcc fails on a stale entry, so this
        cannot silently ship a binary pointing at files that are not there.
    -->
    <qresource prefix="${PREFIX}">
${body}
    </qresource>
</RCC>
`;

writeFileSync(qrcPath, xml);

const bytes = files.reduce((n, f) => n + statSync(f).size, 0);
console.log(
  `[qrc] wrote ${relative(process.cwd(), qrcPath)}: ${files.length} files, ` +
    `${(bytes / 1024).toFixed(0)} KiB raw -> :/notes-editor/`,
);